name: tf_training
channels:
  - defaults
dependencies:
  - _tflow_select
  - absl-py
  - astor
  - backcall
  - blas
  - c-ares
  - ca-certificates
  - certifi
  - cycler
  - dbus
  - decorator
  - expat
  - fontconfig
  - freetype
  - gast
  - glib
  - grpcio
  - gst-plugins-base
  - gstreamer
  - h5py
  - hdf5
  - icu
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - jedi
  - jpeg
  - jupyter_client
  - jupyter_core
  - keras
  - keras-applications
  - keras-base
  - keras-preprocessing
  - kiwisolver
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libpng
  - libprotobuf
  - libsodium
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libxcb
  - libxml2
  - markdown
  - matplotlib
  - mkl
  - mkl_fft
  - mkl_random
  - mock
  - ncurses
  - numpy
  - numpy-base
  - olefile
  - openssl
  - pandas
  - parso
  - patsy
  - pbr
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - prompt_toolkit
  - protobuf
  - ptyprocess
  - pygments
  - pyparsing
  - pyqt
  - python
  - python-dateutil
  - pytz
  - pyyaml
  - pyzmq
  - qt
  - readline
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - sip
  - six
  - sqlite
  - statsmodels
  - tensorboard
  - tensorflow
  - tensorflow-base
  - tensorflow-estimator
  - termcolor
  - tk
  - tornado
  - tqdm
  - traitlets
  - wcwidth
  - werkzeug
  - wheel
  - xz
  - yaml
  - zeromq
  - zlib
  - zstd
  - pip:
    - joblib
    - opencv-python
    - pygal
    - scikit-plot

